**Importing the Dependencies**

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Device Configuration**

In [2]:
# check for CUDA availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


**Data Collection and preprocessing**

In [3]:
# load the breast cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target

In [4]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
print(y[:5])

[0 0 0 0 0]


In [6]:
# split the dataset into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(569, 30)
(455, 30)
(114, 30)


In [8]:
# standardize the data using Standard sclaer
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
type(X_train)

numpy.ndarray

In [10]:
# convert data to PyTorch tensors and move it to GPU
X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train = torch.tensor(y_train, dtype=torch.float32).to(device)
X_test = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test = torch.tensor(y_test, dtype=torch.float32).to(device)

**Neural Network Architecture**

In [11]:
# define the neural network architecture

class NeuralNet(nn.Module):

  def __init__(self, input_size, hidden_size, output_size):
    super(NeuralNet, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, output_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out

In [12]:
# define hyperparameters
input_size = X_train.shape[1]
hidden_size = 64
output_size = 1
learning_rate = 0.001
num_epochs = 1000

In [13]:
# initialize the neural network and move it the GPU
model = NeuralNet(input_size, hidden_size, output_size).to(device)

In [14]:
# define loss and the optiizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

**Training the Neural Network**

In [15]:
# training the model
for epoch in range(num_epochs):
  model.train()
  optimizer.zero_grad()
  outputs = model(X_train)
  loss = criterion(outputs, y_train.view(-1,1))
  loss.backward()
  optimizer.step()

  # claculate accuracy
  with torch.no_grad():
    predicted = outputs.round()
    correct = (predicted == y_train.view(-1,1)).float().sum()
    accuracy = correct/y_train.size(0)

  if (epoch+1) % 10 == 0:
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss : {loss.item():.4f}, Accuracy: {accuracy.item() * 100:.2f}%")

Epoch [10/1000], Loss : 0.5849, Accuracy: 75.38%
Epoch [20/1000], Loss : 0.4705, Accuracy: 90.55%
Epoch [30/1000], Loss : 0.3799, Accuracy: 93.63%
Epoch [40/1000], Loss : 0.3059, Accuracy: 94.51%
Epoch [50/1000], Loss : 0.2480, Accuracy: 95.60%
Epoch [60/1000], Loss : 0.2049, Accuracy: 96.04%
Epoch [70/1000], Loss : 0.1734, Accuracy: 96.92%
Epoch [80/1000], Loss : 0.1503, Accuracy: 97.36%
Epoch [90/1000], Loss : 0.1330, Accuracy: 97.80%
Epoch [100/1000], Loss : 0.1197, Accuracy: 98.24%
Epoch [110/1000], Loss : 0.1092, Accuracy: 98.24%
Epoch [120/1000], Loss : 0.1008, Accuracy: 98.46%
Epoch [130/1000], Loss : 0.0940, Accuracy: 98.46%
Epoch [140/1000], Loss : 0.0882, Accuracy: 98.46%
Epoch [150/1000], Loss : 0.0833, Accuracy: 98.68%
Epoch [160/1000], Loss : 0.0791, Accuracy: 98.68%
Epoch [170/1000], Loss : 0.0754, Accuracy: 98.68%
Epoch [180/1000], Loss : 0.0721, Accuracy: 98.68%
Epoch [190/1000], Loss : 0.0691, Accuracy: 98.68%
Epoch [200/1000], Loss : 0.0665, Accuracy: 98.46%
Epoch [21

**Model Evaluation**

In [16]:
# evaluation on training set
model.eval()
with torch.no_grad():
  outputs = model(X_train)
  predicted = outputs.round()
  correct = (predicted == y_train.view(-1,1)).float().sum()
  accuracy = correct/y_train.size(0)
  print(f"Accuracy on training data: {accuracy.item() * 100:.2f}%")

Accuracy on training data: 100.00%


In [17]:
# evaluation on test set
model.eval()
with torch.no_grad():
  outputs = model(X_test)
  predicted = outputs.round()
  correct = (predicted == y_test.view(-1,1)).float().sum()
  accuracy = correct/y_test.size(0)
  print(f"Accuracy on test data: {accuracy.item() * 100:.2f}%")

Accuracy on test data: 96.49%
